apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5-dev
  template:
    metadata:
      labels:
        app: yolo5-dev
    spec:
      containers:
      - name: yolo5-dev
        image: 352708296901.dkr.ecr.us-east-2.amazonaws.com/edenb27-yolo5-dev:0.0.9
        env:
          - name: images_bucket
            value: "edenb27-cicd-dev"
          - name: queue_name
            value: "edenb27-sqs-dev"
          - name: table_name
            value: "edenb-yolo5-dev"
          - name: request_url
            value: "polybot-service-dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 8081
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 8081
#          initialDelaySeconds: 10
#          periodSeconds: 15


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5-hpa-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5-deployment-dev
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50