apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: 352708296901.dkr.ecr.us-east-2.amazonaws.com/edenb27-polybot-app:0.0.131
        env:
        - name: secret-aws
          value: "EDEN-Poly"
        - name: TELEGRAM_APP_URL
          value: "https://eden-polybot.devops-int-college.com"
        - name: dynamo-table
          value: "edenb-yolo5"
        - name: BUCKET_NAME
          value: "edenb27-docker"
        - name: sqs_url
          value: "https://sqs.us-east-2.amazonaws.com/352708296901/edenb-yolo5"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "105m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443